### ISSUE TITLE
Carts fail to turn at junction rail

### ISSUE THREAD

**Issue by SmartGuy202** [TechReborn/StevesCarts#43]
Galgadorian Hull, Coal Engine, Advanced Control System, Seat, Internal Storage x4. Holding keys to turn on approach to junction rail. GUI acknowledges by filling in the arrows, but cart continues straight as normal. Also does the same weather there is one branch off or two. Also tested at various speeds. Since height has been an issue with some other bugs, will mention feet at Y:69. Using StevesCarts-1.10.2-2.1.3.80.

**Comment by LiEyWe** [comment]
i have the same issue with the newest 1.11.2 version

**Comment by LiEyWe** [comment]
This also happens in the newest 1.12 version

**Comment by Crazierinzane** [comment]
Same issue in All The Mods 3 1.12.
