### ISSUE TITLE
IllegalArgumentException Server Crash with Shooter Module

### ISSUE THREAD

**Issue by Ommina** [TechReborn/StevesCarts#48]
Version 2.1.4.81
Forge 2221

http://pastebin.com/kba5BVhy

Fairly basic cart.  Standard hull.  Shooter module, coal engine, track cleaner (item), side storage.

Cart was placed on the track, filled with arrows and coal, and sent on its way with a 30s timer between arrow fires.  Soon after, sever crashed with the crash-log above.  Server restarted, cart was snatched off the track, server crashed again with the same log (but after cart was harvested and placed into inventory.)

Restarted server a second time, and it's been stable.

**Comment by modmuss50** [comment]
Ok, I can confirm this, its not crashing my client.

**Comment by ranavi** [comment]
Version 2.1.4.83
Forge 2254
Same crash. https://pastebin.com/cfvVzsEZ

Standard Hull, Coal Engine, Advanced Shooter, Experience Bank, Cleaning Machine, Side Chests, Entity  Detector: Monster.
It was trying to shoot at Ancient Golem from Embers mod.
I'm playing on multiplayer server, so i removed the cart after the crash.
