### ISSUE TITLE
Incompatible with Extra Utilities2 Wireless RF Heating Coil

### ISSUE THREAD

**Issue by Corruption-Echoes** [TechReborn/StevesCarts#50]
Stumbled upon an imcompatibility between steves carts and Extra Utilities, When placing a "Wireless RF Heating Coil" from EU in any cart equipped with a Coal engine/Tiny Coal engine the game will instantly crash. Once reloaded the Cart will have moved slightly and the coil will have been destroyed,  I collected logs several times and they are consistently as shown here:
http://pastebin.com/Zjv3GQBK
This happens with both mods updated to their most current versions and no other mods installed, the Cargo manager is unable to insert Coils into carts as a fuel also however it does not cause a crash and merely ignores the coil.

**Comment by modmuss50** [comment]
I dont see this an issue with my mods code. Feel free to correct me.
