### ISSUE TITLE
Steve's Carts 2 not working when offline.

### ISSUE THREAD

**Issue by AntLover** [TechReborn/StevesCarts#53]
Hey!

I've noticed my Steve's Carts 2 cart stops working while offline. I have the area chunkloaded with FTB Utilities but still doesn't work. Is this a bug or is there a work around or something?

Thank you!

P.S. Love the mod, so much fun! Keep it up.

**Comment by modmuss50** [comment]
I think it could be still be an issue with FTB Util

**Comment by modmuss50** [comment]
closing as no response
