### ISSUE TITLE
Woodcutter doesn't plant saplings (1.11.2)

### ISSUE THREAD

**Issue by Blatts12** [TechReborn/StevesCarts#57]
Setup - http://i.imgur.com/fnDLO4X.png
Cart - http://i.imgur.com/S3g4F4Pg.png
Mods - http://i.imgur.com/liBaeEG.png

It's my first time with this mod. Maybe i does somrthing wrong.

**Comment by modmuss50** [comment]
Did you put the coal in the engine?

**Comment by Blatts12** [comment]
Yes

**Comment by modmuss50** [comment]
Humm, ok. I will take a look later.

**Comment by mikr00** [comment]
Also have this isuue
