### ISSUE TITLE
[1.11.2] Attaching upgrades to Cart Assembler creates phantom upgrades

### ISSUE THREAD

**Issue by VampireValik** [TechReborn/StevesCarts#60]
- Minecraft: 1.11.2
- forge-1.11.2-13.20.0.2296
- StevesCarts-1.11.2-2.2.2.12
- RebornCore-1.11.2-2.14.2.94-universal
- No other mods installed.

When attaching an upgrade to a Cart Assembler side there's a chance other sides will gain a phantom upgrade. See the screenshot below. I only attached the Creative upgrade and the other 3 sides suddenly have an upgrade as well. They don't seem to be real. Breaking them (in Survival) drops nothing.

Possibly related, attaching upgrades sometimes results in them being oriented wrong. Instead of mounting against the assembler they will instead be on the opposite side of the block space with a large air gap between the assembler and the upgrade. Unfortunatley I didn't capture a screenshot of this.

I'm not sure how to reproduce these issues. I seem to have them most when I break an upgrade and then replace it. It may also require breaking the Cart Assembler and replacing it and the upgrades. This one just sort of happened when I was testing other things.

![bad upgrades](https://cloud.githubusercontent.com/assets/28024586/25777158/b542d254-32a2-11e7-8f8c-a8eaf6b61a87.png)

**Comment by modmuss50** [comment]
Im not sure why it happens, but I can confirm it.
