### ISSUE TITLE
[1.11.2] Cart Modifier does not work

### ISSUE THREAD

**Issue by VampireValik** [TechReborn/StevesCarts#61]
- Minecraft: 1.11.2
- forge-1.11.2-13.20.0.2296
- StevesCarts-1.11.2-2.2.2.12
- RebornCore-1.11.2-2.14.2.94-universal
- No other mods installed.

The Cart Modifier seems completely broken. I attach it to the side of a Cart Assembler. Then I open the Cart Modifier upgrade interface and insert my cart to be modified. Sometimes the cart gets sucked into the inventory in the middle. Other times it stays in the upper right slot. In either case I can't edit the cart when I open the Cart Assembler. The Cart Assembler appears ready for the creation of a new cart and isn't pre-populated with the cart to be modified.

**Comment by modmuss50** [comment]
Having issues tracking the cause of this down. I will take another look soon

**Comment by nmwael** [comment]
also an issue on 1.12

**Comment by bryanspears** [comment]
Any chance of this being a higher priority? Just ran into this. Tough early game when you can't modify a cart as remaking is expensive.

**Comment by TechnologicApe** [comment]
Is this still being worked on?

**Comment by modmuss50** [comment]
I just spent over an hour trying to debug the issue and failed to do so. When I have a bit more time I would like to rewrite the underlying of the modules so hopefully doing that will solve the issue.

**Comment by DietmarKrause** [comment]
Perhaps related:
https://github.com/TechReborn/StevesCarts/issues/94
