### ISSUE TITLE
[1.11.2] Smelter/Advanced Smelter do not work.

### ISSUE THREAD

**Issue by VampireValik** [TechReborn/StevesCarts#62]
Minecraft: 1.11.2
forge-1.11.2-13.20.0.2296
StevesCarts-1.11.2-2.2.2.12
RebornCore-1.11.2-2.14.2.94-universal
No other mods installed.

If I take something like Oak Wood and click on either slot of the Smelter/Advanced Smelter nothing happens. It doesn't matter if the cart has power and the raw materials in it's inventory, neither smelter functions at all.

**Comment by modmuss50** [comment]
Can confirm, its strange why it happens.
