### ISSUE TITLE
[1.11.2] IC2 Rubber Tree Sapling will not plant with Wood Cutter

### ISSUE THREAD

**Issue by VampireValik** [TechReborn/StevesCarts#63]
- Minecraft: 1.11.2
- forge-1.11.2-13.20.0.2294
- StevesCarts-1.11.2-2.2.3.17
- RebornCore-1.11.2-2.14.2.94-universal
- industrialcraft-2-2.7.12-ex111
- No other mods installed.

Placing an IC2 Rubber Tree Sapling in the Wood Cutter does not result in rubber trees being planted. The Wood Cutter correctly plants vanilla saplings. It also plants Menril saplings from Integrated Dynamics -the only other mod sapling I have available to test with. It does nothing with IC2 rubber saplings, though.

**Comment by modmuss50** [comment]
Im working on adding support for rubber trees now, the cart will not break down the trees but will harvest the rubber into the carts inventory.

**Comment by VampireValik** [comment]
I'm guessing your idea is to somehow simulate the tree tap to get the resin (which could then be passed through a smelter to make rubber)? If so it's an interesting idea but I think most people will still want to harvest the logs to run through an Extractor. I'm not sure which will produce the highest yield, I suspect logs. I wouldn't turn down an addon module that harvests resin before cutting the tree, though. That would overall increase yield a bit.

**Comment by modmuss50** [comment]
I ended up adding a new module, so the default wood cutter cuts the logs and leaves as normal. But when the cart has the tree tap module it will harvest only the rubber sap spots.
