### ISSUE TITLE
Cart with solar module and woodcutter cannot be placed in world

### ISSUE THREAD

**Issue by sintaxcz** [TechReborn/StevesCarts#64]
This is the issue I was facing previously on #40 (which relates to #23).

After "extensive" testing on my heavily-modded world, I figured out that my cart failing to be placed had something to do with solar panels.
Upon creating another instance (this time, just running steve's carts 2 by itself with no other mods), I found that creating a cart containing a solar panel module (of any type, regular/basic/compact) and a woodcutting module (basic/reinforced/galgadorian) in a cart prevents the cart from being placed. You can place the cart if it contains one of these modules, and any other number of modules, but having both installed prevents it from working properly. Any other type of cart works perfectly, this issue is only present with a woodcutter and a solar panel.

I have server with few players who love stevescarts but they cant use them :(

latest 1.10.2 build (StevesCarts-1.10.2-2.1.4.83.jar)

**Comment by modmuss50** [comment]
Can I have the game log of at the time where the cart is being placed

**Comment by modmuss50** [comment]
Need the log, closing.
