### ISSUE TITLE
Backport Rubber Tree Upgrade

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/StevesCarts#65]

**Comment by sandalle** [comment]
After updating to Steve's Carts 1.11.2-2.3.0.22, I see a Tree Tap Module, but there's no texture and Just Enough Items won't show any recipe. I do have the Tree Tap Module enabled: https://github.com/sandalle/nst-exploration-unofficial/blob/master/config/stevescarts.cfg#L85

**Comment by modmuss50** [comment]
Texture, I just dont have one.
Recipe, I forgot to add
